### ISSUE TITLE
Keyboard layout not saving. Reseting to english after reboot!

### ISSUE THREAD

**Issue by SladetBask-Kasper** [nick92/Enso-OS#1]
Hello, I recently found Enso and it is the best operating system I have fount yet, However, there is a small bug that semes to have happend to other ppl as well with normal ubuntu, However the fixes I fount is for unity specifically and does not work under xfce and are in the unity keyboard layout switcher. 

One thing i found that worked but also did not save is to change it with a terminal. the command for swedish keyboard layout is; setxkbmap se
but when i added that into the xfce startup thing it did not work!

Do you Guys have any idea on how to fix this?

**Comment by nick92** [comment]
Hey SladetBask-Kasper,

Glad to hear the like the OS..

So the problem here is that Enso uses Gala as it's window manager which is mainly based on gnome, to make it save you will just need to change the gnome setting. You can change it using the terminal with gsettings by running  - gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'se')"

Or if you download dconf-editor (should have been included in the released OS but we forgot) navigate to org.gnome.desktop.input-sources -> sources and change the 'gb' or 'us' setting to se.

There's a pretty useful question on it here which should give you some further information if it still isn't working: https://askubuntu.com/questions/451945/permanently-set-keyboard-layout-options-with-setxkbmap-in-gnome-unity#582498

Let us know if that works for you

**Comment by SladetBask-Kasper** [comment]
I tried it in a vm today and it seemes to work, I am going to try it on my laptop and it will most likely work :)
Thx.
