### ISSUE TITLE
Time and date at the top seems to be off-centred

### ISSUE THREAD

**Issue by SladetBask-Kasper** [nick92/Enso-OS#2]
Hello, I noticed that the date and time thing at the top bar seems to be off-centered...
At first I thought it was because Of my Indicator icon things pushed to clock thing towards the start button, after loading Enso up in a virtual box i noticed that the clock was still off-centered.

This is not a big deal, I just moved the clock towards the Indicator icons with a small gap in between the indicators and the clock. But it would look better in the center. Any Ideas?

**Comment by nick92** [comment]
Hey  SladetBask-Kasper 

Ye that is a odd issue that we noticed shortly after release unfortunately, been trying to figure out what was causing it for a while and have finally found the solution, which is:

and option in dconf org > gnome > desktop > wm > preferences disable-workarounds should be set to false instead of true. 

`gsettings set org.gnome.desktop.wm.preferences disable-workarounds false`

Hope that solves it for you
