### ISSUE TITLE
Keyboard mapping

### ISSUE THREAD

**Issue by edmorbius** [nick92/Enso-OS#6]
Hi

I just installed 0.1 and it is a very encouraging new distribution.  I have one issue that I can't seem to resolve.  The keyboard mapping doesn't seem to be honored.  During installation, I select US and pc105 yet the mapping seems to be UK.  The pipe is mapped to tilde and the tilde is mapped to some strange character. This also occurs during testing of the iso.

I tried to fix the keyboard configuration using:

sudo dpkg-reconfigure keyboard-configuration

However, the problem persists.  Here is /etc/default/keyboard.  Note that it indicates pc104 after a second attempt to get the mapping correct, which didn't fix the issue.

# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc104"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"

**Comment by nick92** [comment]
Hey edmorbius,

Thank you for trying out our OS and glad to hear that you like it. 

This appears to be a similar issue that has been reported in issue #1 

The problem being around the fact that we use Gala as a WM instead of Xfwm and this causes a bit of a problem around keyboard mappings as you can't amend it unless you go into dconf. 

It's an issue we are aware of and look to solve in the next release.

**Comment by nick92** [comment]
This is now fixed in version 0.3
